import Head from 'next/head';
import {
  Footer,
  Hero,
  SectionFour,
  SectionOne,
  SectionThree,
  SectionTwo,
} from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rise Finance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/svgs/rise-finance.svg" />
      </Head>
      <main>
        <Hero />
        <SectionOne />
        <SectionTwo />
        <SectionThree />
        <SectionFour />
        <Footer />
      </main>
    </>
  );
}
